version: "3.2"

volumes:
  db-data:
  pronunciation-cache:
  wavs:

services:
  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - 15672:15672
    restart: on-failure


  backend:
    build:
      context: backend
    network_mode: host

  module-pronunciation:
    build:
      context: modules/pronunciation/pronunciation-score-icelandic
      dockerfile: ../Dockerfile
    command:
      - --wav-dir=/wavs/
    volumes:
      - pronunciation-cache:/cache
      - wavs:/wavs
    restart: on-failure

  module-scoring:
    build:
      context: modules/scoring
    restart: on-failure
